### ISSUE TITLE
Unknown at-ruleset mangles properties

### ISSUE THREAD

**Issue by bartlomieju** [g-plane/malva#17]
```css
@plugin "daisyui/theme" {
	name: "dark";
	prefersDark: true;
}
```

Output:
```css
@plugin "daisyui/theme" {
  name: "dark";
  prefersdark: true;
}
```

Expected:
```css
@plugin "daisyui/theme" {
  name: "dark";
  prefersDark: true;
}
```

Notice that `prefersDark` has been turned into `prefersdark`.

Originally reported in https://github.com/denoland/deno/issues/26420.
