### ISSUE TITLE
`@media (screen(xl))` required for tailwindcss inside Sass throws syntax error

### ISSUE THREAD

**Issue by RafaelKr** [g-plane/malva#21]
When we use TailwindCSS combined with Sass we need to adjust the `@media screen()` syntax a little as described in their docs:
https://tailwindcss.com/docs/using-with-preprocessors#sass

Unfortunately this breaks malva. It throws
```
Error formatting demo.scss. Message: syntax error at line 1, col 7: expect token `{`, but found `(`
```

demo.scss
```scss
@media (screen(xl)) {
  .element {
      max-width: 30rem;
  }
}
```

**Comment by RafaelKr** [comment]
For now I found the workaround to create the following Sass mixin:

```scss
@mixin media($breakpoint) {
    @media (min-width: theme('screens.#{$breakpoint}')) {
        @content;
    }
}
```

Usage:
```scss
@include media(xl) {
  .element {
      max-width: 30rem;
  }
}
```
