### ISSUE TITLE
long css value like `font-familly` is wrap and it's ugly and no readable

### ISSUE THREAD

**Issue by EKliptus** [g-plane/malva#29]
I have this declaration by example :
```css
#container {
  font-family:
    Inter,
    Roboto,
    "Helvetica Neue",
    "Arial Nova",
    "Nimbus Sans",
    Arial,
    sans-serif;
  height: 100%
};
```

I can't tel to Malva to not wrap it !

So I can use `/* malva-ignore */` but it is not well support in .html file (for me .astro file) : maybe a bug of dprint_plugin_malva or dprint_plugin_markup I dont know, I post here https://github.com/g-plane/markup_fmt/issues/114 for this.
I can use a lower `"printWidth"` for malva , eg : 40 and it work but not in .html or .astro file too !

I presume that `markup-fmt` give the css `<style>` part to malva because I have try it : 

```jsonc
// dprint.json
{
  "lineWidth": 200,
  //... others ...
  "malva": {
    "printWidth": 40,
    //... others ...
}
```

But markup-fmt don't care about malva specific configuration !?
For the `font-family` case :
- printWidth is 40 for css and no wrap = like expected
- printWidth appear to be 200 in html file like in markup config for all html file even for css in style tag !?

**Comment by EKliptus** [comment]
Other example :
```css
.mayclass {
   box-shadow:
      inset 0 0 0 1px rgba(255, 255, 255, 0.12),
      inset 0 -2px 0 rgba(0, 0, 0, 0.24);
}
```
wrap to :
```css
.myclass {
    box-shadow: inset 0 0 0 1px rgba(255, 255, 255, 0.12), inset 0 -2px 0 rgba(0, 0, 0, 0.24);
}
```
