### ISSUE TITLE
FR: grouped declarationOrder sorting

### ISSUE THREAD

**Issue by RafaelKr** [g-plane/malva#31]
In our CSS code we sometimes use empty lines to group things together (especially variables):
```css
:root {
    --color-primary: #000099;
    --color-primary-rgb: 0, 0, 153;

    --color-secondary: #fe8f11;
    --color-secondary-rgb: 254, 143, 17;
}
```

after formatting with `declarationOrder` (we tried `concentric`) all this grouping is lost and becomes:
```css
:root {
    --color-primary: #000099;
    --color-primary-rgb: 0, 0, 153; 
    --color-secondary: #fe8f11;
    --color-secondary-rgb: 254, 143, 17;
}
```

We have a CSS file where we specify variables over 150+ lines of code and it hurts readability a lot when all our grouping is lost.

Would it be possible to add a new `declarationOrderGroupMode` defaulting to false, but if you set it to true it keeps those empty lines and sorts those group blocks instead? Another example which should make it clear how I expect sort groups to work (again, using concentric declarationOrder):
```css
/* before malva */
div {
    background-color: white;
    border-radius: 1rem;

    display: grid;
    column-gap: 1.25rem;

    grid-template-columns: 1fr auto;
    grid-template-areas:
          "a a a"
          "b c c"
          "b c c";
}

/* malva with declarationOrderGroupMode false (current default) */
div {
    display: grid;
    grid-template-columns: 1fr auto;
    grid-template-areas:
        'a a a'
        'b c c'
        'b c c';
    column-gap: 1.25rem;
    border-radius: 1rem;
    background-color: white;
}

/* malva with declarationOrderGroupMode true */
div {
    border-radius: 1rem;
    background-color: white;

    display: grid;
    column-gap: 1.25rem;

    grid-template-columns: 1fr auto;
    grid-template-areas:
          "a a a"
          "b c c"
          "b c c";
}
```
