### ISSUE TITLE
Bug: declarationOrderGroupBy "nonDeclarationAndEmptyLine" fails for my file

### ISSUE THREAD

**Issue by RafaelKr** [g-plane/malva#33]
When I create `tests/fmt/css/declaration-order-group-by/non-declaration-and-empty-line-demo.css` it fails with a `format is unstable` error.
I'm using the main branch (v0.12.0).

```css
/*cfg declarationOrder = "alphabetical"
      declarationOrderGroupBy = "nonDeclarationAndEmptyLine"*/

:root {
    --font-family-primary: 'Arial';

    --color-primary: #00ff00;
    --color-primary-rgb: 0, 255, 0;

    --color-secondary: #0000ff;
    --color-secondary-rgb: 0, 0, 255;
}
```

Did I do something wrong or is this a bug?
