### ISSUE TITLE
Cannot parse the selector `.bg-\\[\\#86efac\\]`

### ISSUE THREAD

**Issue by kt3k** [g-plane/malva#35]
The following css causes syntax error:

```css
.bg-\\[\\#86efac\\] {
  background-color: #86efac;
}
```

I think this is a valid selector. What do you think?

(I found this in [Fresh source code](https://github.com/denoland/fresh/blob/3900aa70d4b305080f42e5814bc832b22aee2d39/init/src/init.ts#L317-L319))
