### ISSUE TITLE
Better `grid-template-*` output

### ISSUE THREAD

**Issue by g-plane** [g-plane/malva#7]
For example, given the code below:

```css
.container {
  grid-template-areas: "toolbar"
                        "main"
                        "menu"
                        "footer";

  grid-template-areas: "menu toolbar"
                       "menu main"
                       "menu footer";

  grid-template-areas: "menu menu toolbar ."
                       "menu menu main toc"
                       "menu menu footer toc";
}
```

[playground](https://malva-play.vercel.app/?code=H4sIAAAAAAAAA42OQQ5AQAxF93OKZvbjAJymKJEwlaqVuLthIrFgTLf%2F9b9fNOwVB08CmwHoZWid0jSPqORQCJcSrDKPNYoNwPvZKVSkYvJrIu6YlcRW5nPBWQB%2FMyKVnBKRTN9TCsWf9naHjyaHjSMuujL7AbjpLISIAQAA&config=H4sIAAAAAAAAA6vmqgUAqLu%2BcwMAAAA%3D&syntax=css)

those CSS values should be kept as input instead of being put on a single line.
