### ISSUE TITLE
support postcss

### ISSUE THREAD

**Issue by clouds56** [g-plane/malva#9]
I'm using postcss which would process `@apply` and `--at-apply`, and following code failed to format. note there's `.` in value.

```css
.text {
  @apply: px-2.5 py-1.5;
}

.text {
  --at-apply: px-2.5 py-1.5;
}
```
Error formatting test.css. Message: Formatting not stable. Bailed after 5 tries. This indicates a bug in the plugin where it formats the file differently each time.
